import { NextResponse } from "next/server";

type MintRequest = {
  company?: string;
  mineral?: string;
  origin?: string;
  volume?: string;
  lotId?: string;
  hash?: string;
  walletAddress?: string;
};

export async function POST(request: Request) {
  try {
    const body = (await request.json()) as MintRequest;

    const lotId = body.lotId || "UNKNOWN-LOT";
    const cleanLot = lotId.replace(/[^a-zA-Z0-9]/g, "").slice(-8);
    const randomSuffix = Math.random().toString(36).slice(2, 8);

    const simulatedAssetId = `cnft_${cleanLot}_${randomSuffix}`;

    return NextResponse.json({
      success: true,
      mode: "simulated",
      assetId: simulatedAssetId,
      network: "solana-devnet",
      message:
        "Simulated cNFT asset ID generated by the backend route. Replace this fallback with Underdog/Solana minting in production.",
      metadata: {
        company: body.company,
        mineral: body.mineral,
        origin: body.origin,
        volume: body.volume,
        lotId: body.lotId,
        hash: body.hash,
        walletAddress: body.walletAddress || null,
      },
    });
  } catch {
    return NextResponse.json(
      {
        success: false,
        message: "Failed to generate Mineral Pass asset.",
      },
      { status: 500 },
    );
  }
}